# Generated by Django 2.2.7 on 2019-11-27 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rated_users',
            field=models.ManyToManyField(related_name='rated_movies', through='movies.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
